kind: pipeline
type: docker
name: CI_CD_LeapHit

trigger:
    event:
      - push

steps:
    - name: Build Docker Image
      image: plugins/docker
      settings:
          dockerfile: code/Dockerfile
          context: code/
          registry: hub.codefirst.iut.uca.fr
          repo: hub.codefirst.iut.uca.fr/LeapHitTeam/leap_hit_server
          username:
            from_secret: SECRET_REGISTRY_USERNAME
          password:
            from_secret: SECRET_REGISTRY_PASSWORD